import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

export const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
  display: 'swap',
});

const newYork = localFont({
  src: './fonts/NewYork.otf',
  variable: '--font-newyork',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.variable} ${newYork.variable} font-pretendard`}
      >
        {children}
      </body>
    </html>
  );
}
