import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

export const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
  display: 'swap',
});

const newYork = localFont({
  src: './fonts/NewYork.otf',
  variable: '--font-newyork',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

  viewport: {
    width: 'device-width',
    initialScale: 1.0,
    maximumScale: 1.0,
    userScalable: false,
    viewportFit: 'cover',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.variable} ${newYork.variable} font-pretendard bg-gray-900 text-white max-w-6xl mx-auto relative flex flex-col min-h-screen-safe scrollbar-hide`}
      >
        {children}
      </body>
    </html>
  );
}
